### PR TITLE
feat: Allow to skip authconfigs by scaffolding too #254

### PR DESCRIPTION
**Pull request by teliatko**
This PR solves #254, by adding `--skip-authconfigs` into `scaffold` command.

I also changed docs and for symmetry adapted also `apply` command.

Please let me know your opinion.

Btw. just subtle suggestion in Google Integration the `authconfigs` are called "auth profiles", at least in GCP web console menu. Maybe it will be worth to have consistent naming in CLI tool like this. I know that naming here is inspired by REST API, but anyway it is confusing.

### CODE REVIEW

**Review by srinandan — CHANGES_REQUESTED** [review]
All the docs are auto generated. Please don't change the docs.

**Comment by teliatko** [comment]
> All the docs are auto generated. Please don't change the docs.

Rolled back, sorry.

**Comment by teliatko** [comment]
@srinandan btw. how the CLA works. I filled it already but in UI at https://cla.developers.google.com/clas I still don't see that it is signed.

**Comment by ssvaidyanathan** [comment]
@teliatko - make sure you are using the same email id in https://cla.developers.google.com/

**Comment by teliatko** [comment]
> @teliatko - make sure you are using the same email id (te****ko​@gmail.com) in https://cla.developers.google.com/

Just checked, I'm 100% sure that the email is correct.

**Comment by ssvaidyanathan** [comment]
@teliatko - looks like the CLA is successful now.

**Review by srinandan — APPROVED** [review]

**Review by srinandan — APPROVED** [review]

**Pull request merged**
